<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<?php if( @$_REQUEST['error'] == 'h') {?>
<div id="messages_product_view"><ul class="messages"><li class="error-msg"><ul><li><span>Error: invalid answer, try again</span></li></ul></li></ul></div>
<?php } ?>

<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>
<div style="margin-bottom: 10px">
    <?php echo Mage::getStoreConfig('contactusmap/contactusmap/contactustoptext') ?>
</div>
<div style="margin-bottom: 10px">
    <strong><?php echo $this->__('Visiting Hours of the Hive') ?></strong></div>
<div style="margin-bottom: 10px">
    <?php echo Mage::getStoreConfig('contactusmap/contactusmap/contactusopeninghour') ?>
</div>
<form action="/contacts/index/post" id="contactForm" method="post" class="scaffold-form">

    <div class="fieldset" style="padding: 0px 0px 15px">

        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>

        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>

        <ul class="form-list">

            <li class="fields">

                <div class="field">

                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>

                    <div class="input-box">

                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml( isset($_SESSION['contact_post']['name']) ? $_SESSION['contact_post']['name'] : $this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />

                    </div>

                </div>

                <div class="field">

                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>

                    <div class="input-box">

                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml( isset($_SESSION['contact_post']['email']) ? $_SESSION['contact_post']['email'] : $this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />

                    </div>

                </div>

            </li>

            <li>

                <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>

                <div class="input-box">

                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="<?php echo trim(@$_SESSION['contact_post']['telephone']) ?>" class="input-text" type="tel" />

                </div>

            </li>

            <li class="wide">

                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>

                <div class="input-box">

                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"><?php echo trim(@$_SESSION['contact_post']['comment']) ?></textarea>

                </div>

            </li>
            <?php
			   $hvFirst  = rand(1,9);
			   $hvSecond =rand(2,10);
			   if( $hvFirst == $hvSecond ) $hvSecond =rand(2,10);
			   $hvResult = md5(($hvFirst+$hvSecond)."HSR-".date("Y-m-d"));
			
			?>  
            <li>
                <label for="honeyspot" class="required"><em>*</em>What the sum of <?php echo "$hvFirst + $hvSecond"?> ?  </label>
                <div class="input-box">
                    <input name="honeyspot" id="honeyspot" value="" class="input-text required-entry <?php if( @$_REQUEST['error'] == 'h') {?>validation-failed<?php } ?>" type="text" />
                    <?php if( @$_REQUEST['error'] == 'h') {?>
                        <div style="" id="advice-required-entry-honeyspot" class="validation-advice">This is a required field.</div>
                    <?php } ?>
                    <input name="honeyspot_hash" id="" value="<?php echo $hvResult?>" type="hidden" />
                </div>
            </li>

        </ul>

    </div>

    <div class="buttons-set" style="margin-left: 0px;">

        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />

        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>

    </div>

</form>

<?php echo $this->getChildHtml("google_map");?>

<script type="text/javascript">

//<![CDATA[

    var contactForm = new VarienForm('contactForm', true);

//]]>

</script>

