<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
       <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
    //]]>
    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
	
	<?php
	$signatureRequired = Mage::getStoreConfig('carriers/linksynceparcel/signature_required');
	if(!$signatureRequired)
	{
		$checkout = Mage::getSingleton('checkout/session');
		$quote = $checkout->getQuote();
		$shippingMethod = $quote->getShippingAddress()->getShippingMethod();
		$code = 'nomethod';
		if(!empty($shippingMethod))
		{
			$methods = Mage::helper('linksynceparcel')->collectShippingData($shippingMethod);
			if(is_array($methods) && isset($methods[0]))
			{
				$code = $methods[0];
			}
		}
	?>
	<div id="authority-to-leave" style="<?php echo (($code == 'linksynceparcel') ? '' : 'display:none')?>">
		<dl class="sp-methods">
			<dt>Authority to leave</dt>
			<dd>
				<ul>
					<li>
						<input type="radio" class="radio authority_to_leave" id="authority_to_leave_1" value="1" name="authority_to_leave">
						<label for="authority_to_leave_1">Do you authorise your delivery to be left if no one is available to sign for it?</label>
					</li>
					<li style="display:none" id="special_instructions">
						<label for="special_instructions">Special Instructions</label>
						<textarea id="special_instructions_text"  name="special_instructions" style="width:100%;" rows="4"></textarea>
						<span>Instructions to be max 128 characters. eg. "leave at side door"</span>
					</li>
				</ul>
			</dd>
		</dl>
	</div>
	<?php
	}
	?>
	
    <div class="buttons-set" id="shipping-method-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" onclick="shippingMethod.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>