<div class="faq-wrap">
<div class="faq">
<?php $faq = $this->getFaq(); ?>
<?php if ($faq):?>

	<div class="faq-head"><?php echo $faq->getQuestion()?></div>
	<div class="faq-detail-answer">
		<?php
			$helperCMS = Mage::helper('cms');
			$processor = $helperCMS->getPageTemplateProcessor();
			$htmlDes = $processor->filter($faq->getAnswer());        
		?>
		<?php echo $htmlDes;?>									
	</div>		
<?php endif ?>


<div class="faq-other-questions">
	<div class="faq-head"><?php echo $this->__('Other questions in the same category');?></div>
	<?php $questions = $this->getOtherQuestions();?>
	<?php if (count($questions)):?>
		<div class="faq-qa">
		<?php foreach ($questions as $_question):?>
			<?php if ($_question->getId() != $faq->getId()):?>
			<li>
				<a href="<?php echo $this->getFaqUrl($_question)?>" title="<?php echo $_question->getQuestion()?>"><?php echo $_question->getQuestion()?></a>
			</li>
			<?php endif;?>
		<?php endforeach;?>
		</div>
	<?php endif;?>
</div>
</div>
</div>