<form action="<?php echo $this->getUrl('testimonials/index/post'); ?>"
      id="testimonialForm"
      class="testimonialForm"
      method="post"
      enctype="multipart/form-data">
	<div class="fieldset">
        
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo $this->__('Your Name (published)') ?></label>
                    <div class="input-box">
                       <input name="name" id="name"
                       title="<?php echo $this->__('Your Name') ?>"
                       value="<?php echo $this->escapeHtml($this->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Your Email Address (not published)') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo $this->__('Your Email Address (not published)') ?>" value="<?php echo $this->escapeHtml($this->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
			</li>
            <li class="fields wide">
                <?php if (Mage::helper('testimonials')->isCompanyEnabled()): ?>
                    <div class="field">
                        <label for="company" class="required"><em>*</em><?php echo $this->__('Subject') ?></label>
                        <div class="input-box">
                            <input name="company" id="company" title="<?php echo $this->__('Subject') ?>" value="<?php echo $this->escapeHtml($this->getCompany()) ?>" class="input-text" type="text" />
                        </div>
                    </div>
                <?php endif ?>
			</li>
			<li <?php if ($this->getLayout()->getBlock('root')
                        ->getTemplate() != "page/3columns.phtml"): ?>class="wide"<?php endif ?>>
                <label for="message" class="required"><em>*</em><?php echo $this->__('Your Message') ?></label>
                <div class="input-box">
                    <textarea name="message" id="message"
                        title="<?php echo $this->__('Your Message') ?>"
                        class="required-entry input-text" cols="5" rows="3"><?php echo $this->getUserMessage(); ?></textarea>
                </div>
            </li>
                
            <li class="fields">  
                <div class="field">
                    <label for="image"><?php echo $this->__('Upload a photo (optional)') ?></label>
                    <div class="input-box">
                        <input name="image" id="image" title="<?php echo $this->__('Image') ?>"
                        type="file" />
                    </div>
                </div>
                <div class="field">
                    <label><?php echo $this->__('How do you rate Queen B ?') ?></label>
                    <div class="input-box">
                    <?php for ($i = 1; $i <= 5; ++$i) { ?>
                        <label for="rating_<?php echo $i; ?>" class="qb-ratingradio"><?php echo $i; ?>
                            <input type="radio" name="rating" id="rating_<?php echo $i; ?>" value="<?php echo $i; ?>" class="radio" <?php if ($this->checkRating($i)): ?>checked="checked"<?php endif; ?> />
                        </label>
                    <?php } ?>
                    </div>
                </div>
            </li>
			
			<li class="fields">  
                <div class="field">
					<?php echo $this->getChildHtml('captcha'); ?>   
                </div>
            </li>
			
			<div class="buttons-set">
				<p class="required"><?php echo $this->__('* Required Fields') ?></p>
				<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
				<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				<button class="button" onclick="setLocation('<?php echo $this->getUrl('testimonials'); ?>'); return false;">
					<span><span><?php echo $this->__('Back') ?></span></span>
				</button>
			</div>

        </ul>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var testimonialForm = new VarienForm('testimonialForm', true);
//]]>
</script>