<?php

	/* @var $hlp Amasty_Scroll_Helper_Data */
	$hlp = Mage::helper('amscroll');
	if (!$hlp->isEnabled()) {
	    return;
	}

	$containerSelector = $hlp->getModuleConfig('advanced/product_container_group');
?>
<script type="text/javascript">
	
	
	var amscroll_object = new amscroll();		
	var amscroll_params = {
		'url'               : '<?php echo str_replace(":8080", "", Mage::helper('core/url')->getCurrentUrl())?>',
		'page'              : '<?php echo intVal($this->getRequest()->getParam('p', 0))?>',
		'actionMode'        : '<?php echo $hlp->getModuleConfig('general/loading')?>',
		'loadingImage'      : '<?php echo $this->getSkinUrl($hlp->getModuleConfig('general/loading_icon')) ?>',
		'pageNumbers'       : '<?php echo $hlp->getModuleConfig('general/page_numbers')?>',
		'loadNextStyle'     : '<?php echo $hlp->getModuleConfig('button/styles')?>',
		'loadingTextButton' : '<?php echo $hlp->getModuleConfig('button/label') ?>',
		'progressbar'       :  <?php echo Zend_Json::encode($hlp->getModuleConfig('info'))?>, 
		'remove_hash'			: '<?php echo $hlp->getModuleConfig('general/remove_hash') ?>',
	};
	
	<?php 
	   foreach($hlp->getModuleConfig('advanced') as $k => $v) { 
	       echo "var amscroll_$k = '$v';";  
	   }
	?>
	document.observe("dom:loaded", function() {
	  if ($$('<?php echo $containerSelector?>').length  != 0 ) {
			amscroll_object.init(amscroll_params); 			
		}
	}); 
  
		
		Event.observe(window, 'scroll', function(event) {
		    if (typeof(amscroll_object) == 'undefined'){
		    return;
		  }		    
		  if ($$('<?php echo $containerSelector?>').length  != 0 ) {
		    amscroll_object.handleScroll();			ewquickview.rewritePage();
		    }
		});
    
   
</script>